//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practic2Abganeev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Taskid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> deadline { get; set; }
        public Nullable<int> priorityid { get; set; }
    
        public virtual TaskPriority TaskPriority { get; set; }
    }
}
